(data_only_dirs .references)

(env
 (release
  (flags
   (:standard
    -warn-error
    +a
    -strict-sequence
    -strict-formats
    -short-paths
    -principal
    -w
    +a-4-9-29-30-40..42-44..46-48-58-66-67)))
 (_
  (flags
   (:standard
    -strict-sequence
    -strict-formats
    -short-paths
    -principal
    -w
    +a-4-9-29-30-40..42-44..46-48-58-66-67))))
