(test
 (name test_wish)
 (package charamel-ssh)
 (modules test_wish)
 (libraries
  alcotest
  alcotest-lwt
  charamel-ssh.wish
  charamel-ssh.keygen
  charamel.tea
  charamel.net
  charamel.os
  charamel.cli
  awa
  base64
  mirage-crypto-ec
  mirage-crypto-pk
  zarith
  lwt
  lwt.unix
  logs
  mirage-crypto-rng.unix
  cstruct
  fmt
  mtime
  test_support
  unix))
