(library
 (name charamel_tea)
 (public_name charamel.tea)
 (modules
  charamel_tea
  key
  mouse
  event
  cmd
  sub
  app
  cursor
  view
  screen
  input
  terminal
  program
  test)
 (libraries
  charamel.ansi
  charamel.colorprofile
  eio
  eio.unix
  eio.mock
  cstruct
  fmt
  mtime
  logs
  unix
  uucp))
