(library
 (name charamel_tea)
 (public_name charamel.tea)
 (modules
  charamel_tea
  key
  mouse
  event
  cmd
  sub
  app
  cursor
  view
  screen
  input
  terminal
  program
  test)
 (libraries
  charamel.ansi
  charamel.colorprofile
  eio
  eio.unix
  eio.mock
  cstruct
  fmt
  mtime
  logs
  unix
  uucp)
 (flags
  (:standard
   -strict-sequence
   -strict-formats
   -short-paths
   -principal
   -w
   +a-4-9-29-30-40..42-44..46-48-58-66-67)))
