(test
 (name test_bubbles)
 (package charamel)
 (libraries
  charamel.bubbles
  charamel.tea
  charamel.ansi
  charamel.lipgloss
  alcotest
  eio
  eio.unix
  eio_main
  fmt
  optint)
 (modules
  test_bubbles
  test_key_binding
  test_fuzzy
  test_duration
  test_cursor
  test_textinput
  test_textarea
  test_viewport
  test_list
  test_table
  test_spinner
  test_progress
  test_paginator
  test_help
  test_timer
  test_stopwatch
  test_filepicker
  test_tree)
 (flags
  (:standard
   -strict-sequence
   -strict-formats
   -short-paths
   -principal
   -w
   +a-4-9-29-30-40..42-44..46-48-58-66-67)))
