(test
 (name test_log)
 (package charm)
 (libraries
  charm.log
  charm.ansi
  charm.colorprofile
  eio
  eio.mock
  logs
  fmt
  jsont
  jsont.bytesrw
  alcotest)
 (flags
  (:standard
   -strict-sequence
   -strict-formats
   -short-paths
   -principal
   -w
   +a-4-9-29-30-40..42-44..46-48-58-66-67)))
