(test
 (name test_gum)
 (package gum)
 (deps %{exe:../../bin/gum/main.exe})
 (modules
  test_gum
  test_format
  test_join
  test_log
  test_style
  test_version
  test_choose
  test_filter
  test_confirm
  test_input
  test_write
  test_pager
  test_csv
  test_table
  test_file
  test_spin)
 (libraries
  gum_core
  alcotest
  charamel.ansi
  charamel.cli
  charamel.bubbles
  charamel.lipgloss
  charamel.tea
  cmdliner
  eio
  eio.unix
  eio_main
  fmt
  logs
  re
  ptime
  test_support
  unix))
