(library
 (name charamel_bubbles)
 (public_name charamel.bubbles)
 (modules
  charamel_bubbles
  key_binding
  fuzzy
  duration
  rune_util
  cursor
  textinput
  textarea
  viewport
  list
  table
  spinner
  progress
  paginator
  help
  timer
  stopwatch
  filepicker
  tree)
 (libraries
  charamel.ansi
  charamel.tea
  charamel.lipgloss
  charamel.harmonica
  fmt
  mtime
  unix
  uucp))
