(library
 (name charamel_fantasy)
 (public_name charamel.fantasy)
 (flags
  (:standard
   -strict-sequence
   -strict-formats
   -short-paths
   -principal
   -w
   +a-4-9-29-30-40..42-44..46-48-58-66-67))
 (libraries
  eio
  eio.unix
  fmt
  logs
  jsont
  jsont.bytesrw
  cohttp-eio
  cohttp
  http
  tls
  tls-eio
  ca-certs
  domain-name
  digestif
  base64
  uri
  ptime
  mirage-crypto-rng))
