(library
 (name charamel_huh)
 (public_name charamel.huh)
 (modules
  charamel_huh
  key
  results
  dyn
  validate
  keymap
  styles
  theme
  env
  field_msg
  accessible
  field_impl
  field_input
  field_text
  field_select
  field_multiselect
  field_confirm
  field_note
  field_file
  group
  layout
  form
  run
  spinner)
 (libraries
  charamel.ansi
  charamel.lipgloss
  charamel.tea
  charamel.bubbles
  eio
  eio.unix
  fmt
  logs
  unix)
 (flags
  (:standard
   -strict-sequence
   -strict-formats
   -short-paths
   -principal
   -w
   +a-4-9-29-30-40..42-44..46-48-58-66-67)))
