(library
 (name charamel_huh)
 (public_name charamel.huh)
 (modules
  charamel_huh
  key
  results
  dyn
  validate
  keymap
  styles
  theme
  env
  field_msg
  accessible
  field_impl
  group
  layout
  form
  run
  spinner)
 (libraries
  charamel.ansi
  charamel.lipgloss
  charamel.tea
  charamel.bubbles
  charamel.os
  lwt
  lwt.unix
  fmt
  logs
  uucp
  unix))
