open Spec

let spec =
  make_spec ~names:[ "bash"; "sh"; "zsh" ]
    ~keywords:
      [
        "if";
        "then";
        "else";
        "elif";
        "fi";
        "for";
        "while";
        "until";
        "do";
        "done";
        "case";
        "esac";
        "function";
        "in";
        "select";
        "time";
        "coproc";
      ]
    ~builtins:
      [
        "echo";
        "printf";
        "read";
        "cd";
        "pwd";
        "pushd";
        "popd";
        "dirs";
        "source";
        "alias";
        "unalias";
        "export";
        "local";
        "readonly";
        "declare";
        "typeset";
        "unset";
        "shift";
        "eval";
        "exec";
        "trap";
        "set";
        "test";
        "getopts";
        "wait";
        "jobs";
        "bg";
        "fg";
        "kill";
        "help";
        "builtin";
        "caller";
        "command";
        "compgen";
        "complete";
        "enable";
        "fc";
        "hash";
        "history";
        "let";
        "mapfile";
        "readarray";
        "shopt";
        "type";
        "ulimit";
        "umask";
        "ls";
        "grep";
        "awk";
        "sed";
        "cat";
        "cp";
        "mv";
        "rm";
        "mkdir";
        "touch";
        "chmod";
        "tar";
        "find";
        "sort";
        "uniq";
        "wc";
        "head";
        "tail";
        "cut";
        "tr";
        "curl";
        "git";
        "sudo";
        "which";
        "env";
      ]
    ~line_comment:[ "#" ]
    ~strings:[ ("\"", "\"", true); ("'", "'", false) ]
    ~raw_strings:[ ("`", "`") ]
    ~number:
      (alt [ seq [ str "0x"; rep1 (set "0123456789abcdefABCDEF") ]; integer_number ])
    ~ident:identifier
    ~operators:
      [
        "&&";
        "||";
        ";;";
        "==";
        "!=";
        "<=";
        ">=";
        "<<";
        ">>";
        "|";
        "&";
        "<";
        ">";
        "-";
        "+";
        "*";
        "/";
        "%";
        "=";
        "!";
        "^";
        "~";
        "?";
        "$";
      ]
    ~attribute:
      (Some
         (alt
            [
              seq [ str "${"; rep (not_chars "}\n"); str "}" ];
              seq
                [
                  str "$";
                  set "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_";
                  rep
                    (set "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_");
                ];
              seq [ str "$"; set "0123456789@*#?$!-" ];
            ]))
    ()
