open Spec

let spec =
  make_spec ~names:[ "c"; "h" ]
    ~keywords:
      [
        "auto";
        "break";
        "case";
        "const";
        "continue";
        "default";
        "do";
        "else";
        "enum";
        "extern";
        "for";
        "goto";
        "if";
        "inline";
        "register";
        "restrict";
        "return";
        "sizeof";
        "static";
        "struct";
        "switch";
        "typedef";
        "union";
        "volatile";
        "while";
        "_Alignas";
        "_Alignof";
        "_Atomic";
        "_Bool";
        "_Complex";
        "_Generic";
        "_Noreturn";
        "_Static_assert";
        "_Thread_local";
        "#include";
        "#define";
        "#ifndef";
        "#ifdef";
        "#if";
        "#else";
        "#elif";
        "#endif";
        "#undef";
        "#pragma";
        "#error";
      ]
    ~types:
      [
        "bool";
        "char";
        "double";
        "float";
        "int";
        "long";
        "short";
        "signed";
        "unsigned";
        "void";
        "size_t";
        "ssize_t";
        "ptrdiff_t";
        "int8_t";
        "int16_t";
        "int32_t";
        "int64_t";
        "uint8_t";
        "uint16_t";
        "uint32_t";
        "uint64_t";
        "intptr_t";
        "uintptr_t";
        "FILE";
        "time_t";
      ]
    ~builtins:
      [
        "printf";
        "scanf";
        "fprintf";
        "sprintf";
        "snprintf";
        "malloc";
        "calloc";
        "realloc";
        "free";
        "memcpy";
        "memset";
        "memmove";
        "strlen";
        "strcpy";
        "strncpy";
        "strcmp";
        "strncmp";
        "strcat";
        "strstr";
        "fopen";
        "fclose";
        "fread";
        "fwrite";
        "puts";
        "getchar";
        "putchar";
        "exit";
        "abort";
        "assert";
      ]
    ~constants:[ "NULL"; "true"; "false"; "EOF" ]
    ~line_comment:[ "//" ]
    ~block_comment:[ ("/*", "*/") ]
    ~strings:[ ("\"", "\"", true); ("'", "'", true) ]
    ~number:c_number ~ident:identifier
    ~operators:
      [
        "->";
        "++";
        "--";
        "<<=";
        ">>=";
        "<=";
        ">=";
        "==";
        "!=";
        "&&";
        "||";
        "+=";
        "-=";
        "*=";
        "/=";
        "%=";
        "&=";
        "^=";
        "|=";
        "<<";
        ">>";
        "+";
        "-";
        "*";
        "/";
        "%";
        "<";
        ">";
        "=";
        "!";
        "&";
        "|";
        "^";
        "~";
        "?";
        ":";
        ".";
      ]
    ()
