open Spec

let spec =
  make_spec
    ~names:[ "cpp"; "cc"; "cxx"; "hpp"; "hh"; "hxx"; "c++" ]
    ~keywords:
      [
        "auto";
        "break";
        "case";
        "catch";
        "class";
        "const";
        "consteval";
        "constexpr";
        "constinit";
        "continue";
        "default";
        "delete";
        "do";
        "else";
        "enum";
        "explicit";
        "export";
        "extern";
        "for";
        "friend";
        "if";
        "inline";
        "namespace";
        "new";
        "noexcept";
        "nullptr";
        "operator";
        "private";
        "protected";
        "public";
        "return";
        "static";
        "static_assert";
        "struct";
        "switch";
        "template";
        "this";
        "throw";
        "try";
        "typedef";
        "typename";
        "union";
        "using";
        "virtual";
        "volatile";
        "while";
        "override";
        "final";
        "concept";
        "requires";
        "co_await";
        "co_yield";
        "co_return";
        "module";
        "import";
        "#include";
        "#define";
        "#ifdef";
        "#ifndef";
        "#endif";
      ]
    ~types:
      [
        "bool";
        "char";
        "double";
        "float";
        "int";
        "long";
        "short";
        "signed";
        "unsigned";
        "void";
        "size_t";
        "string";
        "wstring";
        "u16string";
        "u32string";
        "vector";
        "map";
        "set";
        "unordered_map";
      ]
    ~builtins:
      [
        "printf";
        "scanf";
        "malloc";
        "free";
        "memcpy";
        "strlen";
        "cout";
        "cin";
        "cerr";
        "endl";
        "move";
        "forward";
        "make_unique";
        "make_shared";
        "make_pair";
      ]
    ~constants:[ "NULL"; "true"; "false"; "nullptr"; "EOF" ]
    ~line_comment:C.spec.line_comment ~block_comment:C.spec.block_comment
    ~strings:C.spec.strings
    ~raw_strings:[ ("R\"(", ")\"") ]
    ~number:C.spec.number ~ident:C.spec.ident
    ~operators:([ "->*"; ".*"; "::" ] @ C.spec.operators)
    ~attribute:(Some (Re.seq [ Re.str "[["; Re.rep (not_chars "]\n"); Re.str "]]" ]))
    ()
