open Spec

let spec =
  make_spec
    ~names:[ "javascript"; "js"; "mjs"; "cjs" ]
    ~keywords:
      [
        "as";
        "async";
        "await";
        "break";
        "case";
        "catch";
        "class";
        "const";
        "continue";
        "debugger";
        "default";
        "delete";
        "do";
        "else";
        "enum";
        "export";
        "extends";
        "finally";
        "for";
        "from";
        "function";
        "get";
        "if";
        "import";
        "in";
        "instanceof";
        "let";
        "new";
        "of";
        "return";
        "set";
        "static";
        "super";
        "switch";
        "this";
        "throw";
        "try";
        "typeof";
        "var";
        "void";
        "while";
        "with";
        "yield";
      ]
    ~builtins:
      [
        "console";
        "window";
        "document";
        "Array";
        "Boolean";
        "Date";
        "Error";
        "Function";
        "JSON";
        "Math";
        "Number";
        "Object";
        "String";
        "RegExp";
        "Symbol";
        "Map";
        "Set";
        "Promise";
        "Proxy";
        "Reflect";
        "BigInt";
        "parseInt";
        "parseFloat";
        "isNaN";
        "isFinite";
        "decodeURI";
        "decodeURIComponent";
        "encodeURI";
        "encodeURIComponent";
        "eval";
        "setTimeout";
        "setInterval";
      ]
    ~constants:[ "true"; "false"; "null"; "undefined"; "NaN"; "Infinity"; "globalThis" ]
    ~line_comment:[ "//" ]
    ~block_comment:[ ("/*", "*/") ]
    ~strings:[ ("\"", "\"", true); ("'", "'", true) ]
    ~raw_strings:[ ("`", "`") ]
    ~number:
      (Re.alt
         [
           hex_literal ~suffix:(Re.str "n") ();
           Re.seq [ Re.str "0b"; Re.rep1 (Re.set "01"); Re.opt (Re.str "n") ];
           Re.seq [ Re.str "0o"; Re.rep1 (Re.set "01234567"); Re.opt (Re.str "n") ];
           Re.seq [ decimal; Re.opt (Re.str "n") ];
         ])
    ~ident:identifier_dollar
    ~operators:
      [
        "!==";
        "===";
        "=>";
        "**=";
        "&&=";
        "||=";
        "??=";
        "...";
        "?.";
        "**";
        "&&";
        "||";
        "??";
        "==";
        "!=";
        "<=";
        ">=";
        "+=";
        "-=";
        "*=";
        "/=";
        "%=";
        "&=";
        "|=";
        "^=";
        "<<";
        ">>";
        "++";
        "--";
        "+";
        "-";
        "*";
        "/";
        "%";
        "<";
        ">";
        "=";
        "!";
        "&";
        "|";
        "^";
        "?";
        ":";
      ]
    ()
