open Spec

let spec =
  make_spec ~names:[ "java" ]
    ~keywords:
      [
        "abstract";
        "assert";
        "break";
        "case";
        "catch";
        "class";
        "const";
        "continue";
        "default";
        "do";
        "else";
        "enum";
        "extends";
        "final";
        "finally";
        "for";
        "goto";
        "if";
        "implements";
        "import";
        "instanceof";
        "interface";
        "native";
        "new";
        "package";
        "private";
        "protected";
        "public";
        "return";
        "static";
        "strictfp";
        "super";
        "switch";
        "synchronized";
        "this";
        "throw";
        "throws";
        "transient";
        "try";
        "volatile";
        "while";
        "var";
        "record";
        "sealed";
        "permits";
        "yield";
      ]
    ~types:
      [
        "boolean";
        "byte";
        "char";
        "double";
        "float";
        "int";
        "long";
        "short";
        "void";
        "String";
        "Integer";
        "Boolean";
        "Double";
        "Float";
        "Object";
      ]
    ~builtins:
      [
        "System";
        "out";
        "err";
        "println";
        "print";
        "printf";
        "length";
        "equals";
        "hashCode";
        "toString";
        "valueOf";
        "size";
        "get";
        "add";
        "remove";
        "isEmpty";
        "contains";
        "Math";
        "sqrt";
        "pow";
        "abs";
        "max";
        "min";
      ]
    ~constants:[ "true"; "false"; "null" ] ~line_comment:[ "//" ]
    ~block_comment:[ ("/*", "*/") ]
    ~strings:[ ("\"", "\"", true); ("'", "'", true) ]
    ~raw_strings:[ ("\"\"\"", "\"\"\"") ]
    ~number:
      (Re.alt
         [
           hex_literal ~suffix:(Re.set "lLfFdD") ();
           Re.seq [ Re.str "0b"; Re.rep1 (Re.set "01"); Re.opt (Re.set "lLfFdD") ];
           Re.seq [ decimal; Re.opt (Re.set "lLfFdD") ];
         ])
    ~ident:identifier
    ~operators:
      [
        ">>>=";
        ">>>";
        "<<=";
        ">>=";
        "->";
        "++";
        "--";
        "==";
        "!=";
        "<=";
        ">=";
        "&&";
        "||";
        "+=";
        "-=";
        "*=";
        "/=";
        "%=";
        "&=";
        "|=";
        "^=";
        "<<";
        ">>";
        "+";
        "-";
        "*";
        "/";
        "%";
        "<";
        ">";
        "=";
        "!";
        "&";
        "|";
        "^";
        "~";
        "?";
        ":";
      ]
    ~attribute:
      (Some
         (Re.seq [ Re.str "@"; identifier; Re.rep (Re.seq [ Re.str "."; identifier ]) ]))
    ()
