open Spec

let spec =
  make_spec ~names:[ "kotlin"; "kt"; "kts" ]
    ~keywords:
      [
        "as";
        "break";
        "class";
        "continue";
        "do";
        "else";
        "for";
        "fun";
        "if";
        "in";
        "!in";
        "interface";
        "is";
        "!is";
        "null";
        "object";
        "package";
        "return";
        "super";
        "this";
        "throw";
        "try";
        "typealias";
        "typeof";
        "val";
        "var";
        "when";
        "while";
        "by";
        "get";
        "set";
        "import";
        "field";
        "where";
        "abstract";
        "annotation";
        "companion";
        "const";
        "crossinline";
        "data";
        "enum";
        "expect";
        "external";
        "final";
        "infix";
        "inline";
        "inner";
        "internal";
        "lateinit";
        "noinline";
        "open";
        "operator";
        "out";
        "override";
        "private";
        "protected";
        "public";
        "reified";
        "sealed";
        "suspend";
        "tailrec";
        "vararg";
      ]
    ~types:
      [
        "Int";
        "Long";
        "Short";
        "Byte";
        "Double";
        "Float";
        "Boolean";
        "Char";
        "String";
        "Unit";
        "Any";
        "Nothing";
        "Array";
        "List";
        "Map";
        "Set";
        "MutableList";
        "MutableMap";
        "MutableSet";
      ]
    ~builtins:
      [
        "println";
        "print";
        "listOf";
        "mapOf";
        "setOf";
        "mutableListOf";
        "arrayOf";
        "lazy";
        "let";
        "run";
        "with";
        "apply";
        "also";
        "takeIf";
        "takeUnless";
        "check";
        "require";
        "error";
        "TODO";
      ]
    ~constants:[ "true"; "false"; "null" ] ~line_comment:[ "//" ]
    ~block_comment:[ ("/*", "*/") ]
    ~strings:[ ("\"", "\"", true); ("'", "'", true) ]
    ~raw_strings:[ ("\"\"\"", "\"\"\"") ]
    ~number:
      (alt
         [
           seq [ str "0x"; rep1 (set "0123456789abcdefABCDEF"); opt (set "LlFfUu") ];
           seq [ str "0b"; rep1 (set "01"); opt (set "LlFfUu") ];
           seq [ decimal; opt (set "LlFfUu") ];
         ])
    ~ident:identifier
    ~operators:
      [
        "!==";
        "===";
        "?.";
        "?:";
        "::";
        "->";
        "==";
        "!=";
        "<=";
        ">=";
        "&&";
        "||";
        "..>";
        "..";
        "+=";
        "-=";
        "*=";
        "/=";
        "%=";
        "++";
        "--";
        "+";
        "-";
        "*";
        "/";
        "%";
        "<";
        ">";
        "=";
        "!";
        "&";
        "|";
        "^";
        "?";
        ":";
      ]
    ~attribute:(Some (seq [ str "@"; identifier; rep (seq [ str "."; identifier ]) ]))
    ()
