open Spec

let spec =
  make_spec ~names:[ "php" ]
    ~keywords:
      [
        "abstract";
        "and";
        "array";
        "as";
        "break";
        "callable";
        "case";
        "catch";
        "class";
        "clone";
        "const";
        "continue";
        "declare";
        "default";
        "do";
        "echo";
        "else";
        "elseif";
        "enddeclare";
        "endfor";
        "endforeach";
        "endif";
        "endswitch";
        "endwhile";
        "extends";
        "final";
        "finally";
        "fn";
        "for";
        "foreach";
        "function";
        "global";
        "goto";
        "if";
        "implements";
        "include";
        "include_once";
        "instanceof";
        "insteadof";
        "interface";
        "isset";
        "list";
        "match";
        "namespace";
        "new";
        "or";
        "print";
        "private";
        "protected";
        "public";
        "readonly";
        "require";
        "require_once";
        "return";
        "static";
        "switch";
        "throw";
        "trait";
        "try";
        "unset";
        "use";
        "var";
        "while";
        "xor";
        "yield";
      ]
    ~types:
      [
        "int";
        "float";
        "bool";
        "string";
        "array";
        "object";
        "callable";
        "void";
        "iterable";
        "mixed";
        "never";
        "static";
        "self";
        "parent";
      ]
    ~builtins:
      [
        "strlen";
        "count";
        "var_dump";
        "print_r";
        "array_map";
        "array_filter";
        "array_push";
        "implode";
        "explode";
        "str_replace";
        "sprintf";
        "printf";
        "json_encode";
        "json_decode";
        "fopen";
        "fwrite";
        "fclose";
        "preg_match";
        "preg_replace";
        "strtoupper";
        "strtolower";
      ]
    ~constants:
      [
        "true";
        "false";
        "null";
        "__DIR__";
        "__FILE__";
        "__LINE__";
        "__CLASS__";
        "__FUNCTION__";
        "__METHOD__";
        "__NAMESPACE__";
      ]
    ~line_comment:[ "//"; "#" ]
    ~block_comment:[ ("/*", "*/") ]
    ~strings:[ ("\"", "\"", true); ("'", "'", true) ]
    ~number:
      (Re.alt
         [
           hex_literal ();
           Re.seq [ Re.str "0b"; Re.rep1 (Re.set "01") ];
           Re.seq [ Re.str "0o"; Re.rep1 (Re.set "01234567") ];
           decimal;
         ])
    ~ident:identifier
    ~operators:
      [
        "<=>";
        "??=";
        "??";
        "->";
        "::";
        "===";
        "!==";
        "==";
        "!=";
        "<=";
        ">=";
        "&&";
        "||";
        "+=";
        "-=";
        "*=";
        "/=";
        "%=";
        ".=";
        "++";
        "--";
        "+";
        "-";
        "*";
        "/";
        "%";
        "<";
        ">";
        "=";
        "!";
        "&";
        "|";
        "^";
        "~";
        "?";
        ".";
      ]
    ~attribute:
      (Some
         (Re.alt
            [
              Re.seq [ Re.str "#["; Re.rep (not_chars "]\n"); Re.str "]" ];
              Re.seq [ Re.str "$"; ident_tail; Re.rep ident_tail ];
            ]))
    ~case_sensitive:false ()
