open Spec

let spec =
  make_spec ~names:[ "python"; "py"; "py3" ]
    ~keywords:
      [
        "and";
        "as";
        "assert";
        "async";
        "await";
        "break";
        "class";
        "continue";
        "def";
        "del";
        "elif";
        "else";
        "except";
        "finally";
        "for";
        "from";
        "global";
        "if";
        "import";
        "in";
        "is";
        "lambda";
        "nonlocal";
        "not";
        "or";
        "pass";
        "raise";
        "return";
        "try";
        "while";
        "with";
        "yield";
        "match";
        "case";
      ]
    ~types:
      [
        "int";
        "float";
        "str";
        "bool";
        "bytes";
        "list";
        "dict";
        "set";
        "tuple";
        "frozenset";
        "complex";
        "object";
        "type";
        "bytearray";
      ]
    ~builtins:
      [
        "abs";
        "all";
        "any";
        "ascii";
        "bin";
        "callable";
        "chr";
        "classmethod";
        "compile";
        "complex";
        "delattr";
        "dict";
        "dir";
        "divmod";
        "enumerate";
        "eval";
        "exec";
        "filter";
        "float";
        "format";
        "frozenset";
        "getattr";
        "globals";
        "hasattr";
        "hash";
        "help";
        "hex";
        "id";
        "input";
        "isinstance";
        "issubclass";
        "iter";
        "len";
        "list";
        "locals";
        "map";
        "max";
        "min";
        "next";
        "object";
        "open";
        "ord";
        "pow";
        "print";
        "property";
        "range";
        "repr";
        "reversed";
        "round";
        "set";
        "setattr";
        "slice";
        "sorted";
        "staticmethod";
        "str";
        "sum";
        "super";
        "tuple";
        "type";
        "vars";
        "zip";
      ]
    ~constants:[ "True"; "False"; "None"; "NotImplemented"; "Ellipsis" ]
    ~line_comment:[ "#" ]
    ~strings:[ ("\"", "\"", true); ("'", "'", true) ]
    ~raw_strings:[ ("\"\"\"", "\"\"\""); ("'''", "'''") ]
    ~number:python_number ~ident:identifier
    ~operators:
      [
        "**=";
        "//=";
        ">>=";
        "<<=";
        "==";
        "!=";
        "<=";
        ">=";
        "+=";
        "-=";
        "*=";
        "/=";
        "%=";
        "&=";
        "|=";
        "^=";
        ">>";
        "<<";
        "**";
        "//";
        "->";
        ":=";
        "@";
        "+";
        "-";
        "*";
        "/";
        "%";
        "<";
        ">";
        "=";
        "&";
        "|";
        "^";
        "~";
        ".";
      ]
    ~attribute:(Some (seq [ str "@"; identifier; rep (seq [ str "."; identifier ]) ]))
    ()
