open Spec

let spec =
  make_spec ~names:[ "rust"; "rs" ]
    ~keywords:
      [
        "as";
        "async";
        "await";
        "break";
        "const";
        "continue";
        "crate";
        "dyn";
        "else";
        "enum";
        "extern";
        "fn";
        "for";
        "if";
        "impl";
        "in";
        "let";
        "loop";
        "match";
        "mod";
        "move";
        "mut";
        "pub";
        "ref";
        "return";
        "self";
        "Self";
        "static";
        "struct";
        "super";
        "trait";
        "type";
        "unsafe";
        "use";
        "where";
        "while";
      ]
    ~types:
      [
        "bool";
        "char";
        "f32";
        "f64";
        "i8";
        "i16";
        "i32";
        "i64";
        "i128";
        "isize";
        "str";
        "u8";
        "u16";
        "u32";
        "u64";
        "u128";
        "usize";
        "String";
        "Vec";
        "Option";
        "Result";
        "Box";
      ]
    ~builtins:
      [
        "println";
        "print";
        "format";
        "format_args";
        "vec";
        "panic";
        "assert";
        "assert_eq";
        "assert_ne";
        "debug_assert";
        "debug_assert_eq";
        "todo";
        "unimplemented";
        "write";
        "writeln";
        "matches";
        "env";
        "concat";
        "stringify";
        "include";
        "include_str";
        "include_bytes";
        "line";
        "column";
        "file";
        "module_path";
        "cfg";
      ]
    ~constants:[ "true"; "false"; "Some"; "None"; "Ok"; "Err" ]
    ~line_comment:[ "//" ]
    ~block_comment:[ ("/*", "*/") ]
    ~strings:[ ("\"", "\"", true); ("'", "'", true) ]
    ~raw_strings:[ ("br#\"", "\"#"); ("r#\"", "\"#"); ("br\"", "\""); ("r\"", "\"") ]
    ~number:rust_number ~ident:identifier
    ~operators:
      [
        "..=";
        "<<=";
        ">>=";
        "->";
        "=>";
        "::";
        "&&";
        "||";
        "==";
        "!=";
        "<=";
        ">=";
        "+=";
        "-=";
        "*=";
        "/=";
        "%=";
        "^=";
        "&=";
        "|=";
        "<<";
        ">>";
        "..";
        "!";
        "?";
        "+";
        "-";
        "*";
        "/";
        "%";
        "<";
        ">";
        "=";
        "&";
        "|";
        "^";
        "@";
      ]
    ~attribute:
      (Some (seq [ str "#"; opt (str "!"); str "["; rep (not_chars "]\n"); str "]" ]))
    ()
