open Spec

let spec =
  make_spec ~names:[ "sql" ]
    ~keywords:
      [
        "select";
        "from";
        "where";
        "insert";
        "into";
        "values";
        "update";
        "set";
        "delete";
        "create";
        "table";
        "drop";
        "alter";
        "add";
        "column";
        "primary";
        "key";
        "foreign";
        "references";
        "unique";
        "index";
        "view";
        "trigger";
        "procedure";
        "join";
        "inner";
        "left";
        "right";
        "full";
        "outer";
        "cross";
        "on";
        "group";
        "by";
        "order";
        "having";
        "limit";
        "offset";
        "union";
        "all";
        "distinct";
        "as";
        "and";
        "or";
        "not";
        "is";
        "in";
        "exists";
        "between";
        "like";
        "glob";
        "case";
        "when";
        "then";
        "else";
        "end";
        "cast";
        "begin";
        "commit";
        "rollback";
        "transaction";
        "grant";
        "revoke";
        "with";
        "recursive";
        "returning";
        "default";
        "constraint";
        "check";
        "cascade";
        "if";
      ]
    ~types:
      [
        "int";
        "integer";
        "smallint";
        "bigint";
        "decimal";
        "numeric";
        "real";
        "float";
        "double";
        "precision";
        "char";
        "character";
        "varchar";
        "nvarchar";
        "text";
        "clob";
        "blob";
        "boolean";
        "date";
        "time";
        "timestamp";
        "interval";
        "serial";
        "uuid";
        "json";
        "jsonb";
        "array";
        "enum";
        "bytea";
      ]
    ~builtins:
      [
        "count";
        "sum";
        "avg";
        "min";
        "max";
        "coalesce";
        "nullif";
        "ifnull";
        "abs";
        "round";
        "length";
        "substr";
        "substring";
        "upper";
        "lower";
        "trim";
        "ltrim";
        "rtrim";
        "replace";
        "concat";
        "now";
        "current_date";
        "current_time";
        "current_timestamp";
        "date";
        "strftime";
        "random";
        "group_concat";
        "last_insert_rowid";
        "total";
        "typeof";
      ]
    ~constants:[ "true"; "false"; "null"; "unknown" ]
    ~line_comment:[ "--" ]
    ~block_comment:[ ("/*", "*/") ]
    ~strings:[ ("'", "'", false); ("\"", "\"", false) ]
    ~number:float_number
    ~ident:
      (Re.seq
         [
           Re.set "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_";
           Re.rep
             (Re.set "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_$");
         ])
    ~operators:
      [
        "->>";
        "->";
        "<>";
        "!=";
        "<=";
        ">=";
        "||";
        "::";
        "+";
        "-";
        "*";
        "/";
        "%";
        "<";
        ">";
        "=";
      ]
    ~case_sensitive:false ()
