open Spec

let spec =
  make_spec ~names:[ "swift" ]
    ~keywords:
      [
        "associatedtype";
        "class";
        "deinit";
        "enum";
        "extension";
        "fileprivate";
        "func";
        "import";
        "init";
        "inout";
        "internal";
        "let";
        "open";
        "operator";
        "private";
        "protocol";
        "public";
        "rethrows";
        "static";
        "struct";
        "subscript";
        "typealias";
        "var";
        "break";
        "case";
        "continue";
        "default";
        "defer";
        "do";
        "else";
        "fallthrough";
        "for";
        "guard";
        "if";
        "in";
        "repeat";
        "return";
        "switch";
        "where";
        "while";
        "as";
        "Any";
        "catch";
        "is";
        "nil";
        "super";
        "self";
        "Self";
        "throw";
        "throws";
        "try";
        "await";
        "async";
        "lazy";
        "weak";
        "unowned";
        "willSet";
        "didSet";
        "get";
        "set";
        "some";
        "any";
      ]
    ~types:
      [
        "Int";
        "Int8";
        "Int16";
        "Int32";
        "Int64";
        "UInt";
        "UInt8";
        "UInt16";
        "UInt32";
        "UInt64";
        "Double";
        "Float";
        "Bool";
        "String";
        "Character";
        "Array";
        "Dictionary";
        "Set";
        "Optional";
        "AnyObject";
        "Void";
        "Never";
      ]
    ~builtins:
      [
        "print";
        "map";
        "filter";
        "reduce";
        "compactMap";
        "flatMap";
        "append";
        "count";
        "isEmpty";
        "max";
        "min";
        "sorted";
        "forEach";
      ]
    ~constants:[ "true"; "false"; "nil" ] ~line_comment:[ "//" ]
    ~block_comment:[ ("/*", "*/") ]
    ~strings:[ ("\"", "\"", true); ("'", "'", true) ]
    ~raw_strings:[ ("#\"\"\"", "\"\"\"#"); ("#\"", "\"#") ]
    ~number:
      (alt
         [
           seq [ str "0x"; rep1 (set "0123456789abcdefABCDEF") ];
           seq [ str "0o"; rep1 (set "01234567") ];
           seq [ str "0b"; rep1 (set "01") ];
           decimal;
         ])
    ~ident:identifier
    ~operators:
      [
        "??";
        "?.";
        "->";
        "...";
        "..<";
        "===";
        "!==";
        "==";
        "!=";
        "<=";
        ">=";
        "&&";
        "||";
        "+=";
        "-=";
        "*=";
        "/=";
        "%=";
        "++";
        "--";
        "+";
        "-";
        "*";
        "/";
        "%";
        "<";
        ">";
        "=";
        "!";
        "&";
        "|";
        "^";
        "?";
        ":";
      ]
    ~attribute:(Some (seq [ str "@"; identifier ]))
    ()
