open Spec

let spec =
  make_spec ~names:[ "typescript"; "ts"; "tsx" ]
    ~keywords:
      [
        "abstract";
        "any";
        "as";
        "asserts";
        "async";
        "await";
        "boolean";
        "break";
        "case";
        "catch";
        "class";
        "const";
        "constructor";
        "continue";
        "debugger";
        "declare";
        "default";
        "delete";
        "do";
        "else";
        "enum";
        "export";
        "extends";
        "finally";
        "for";
        "from";
        "function";
        "get";
        "if";
        "implements";
        "import";
        "infer";
        "in";
        "instanceof";
        "interface";
        "is";
        "keyof";
        "let";
        "module";
        "namespace";
        "never";
        "new";
        "null";
        "number";
        "object";
        "of";
        "out";
        "package";
        "private";
        "protected";
        "public";
        "readonly";
        "require";
        "return";
        "satisfies";
        "set";
        "static";
        "string";
        "super";
        "switch";
        "symbol";
        "this";
        "throw";
        "try";
        "type";
        "typeof";
        "undefined";
        "unique";
        "unknown";
        "var";
        "void";
        "while";
        "with";
        "yield";
      ]
    ~types:
      [
        "Array";
        "ReadonlyArray";
        "Promise";
        "Record";
        "Partial";
        "Required";
        "Pick";
        "Omit";
        "Map";
        "Set";
        "Date";
        "RegExp";
        "Error";
      ]
    ~builtins:
      [
        "console";
        "window";
        "document";
        "JSON";
        "Math";
        "Number";
        "Object";
        "String";
        "Boolean";
        "parseInt";
        "parseFloat";
        "setTimeout";
        "setInterval";
      ]
    ~constants:[ "true"; "false"; "null"; "undefined"; "NaN"; "Infinity" ]
    ~line_comment:[ "//" ]
    ~block_comment:[ ("/*", "*/") ]
    ~strings:[ ("\"", "\"", true); ("'", "'", true) ]
    ~raw_strings:[ ("`", "`") ]
    ~number:Javascript.spec.number ~ident:identifier_dollar
    ~operators:Javascript.spec.operators ()
