open Spec

let spec =
  make_spec ~names:[ "zig" ]
    ~keywords:
      [
        "addrspace";
        "align";
        "allowzero";
        "and";
        "anyframe";
        "anytype";
        "asm";
        "async";
        "await";
        "break";
        "callconv";
        "catch";
        "comptime";
        "const";
        "continue";
        "defer";
        "else";
        "enum";
        "errdefer";
        "export";
        "extern";
        "fn";
        "for";
        "if";
        "inline";
        "noalias";
        "noinline";
        "nosuspend";
        "opaque";
        "or";
        "orelse";
        "packed";
        "pub";
        "resume";
        "struct";
        "suspend";
        "switch";
        "test";
        "threadlocal";
        "try";
        "union";
        "usingnamespace";
        "var";
        "volatile";
        "while";
      ]
    ~types:
      [
        "bool";
        "f16";
        "f32";
        "f64";
        "f128";
        "i8";
        "i16";
        "i32";
        "i64";
        "i128";
        "isize";
        "u8";
        "u16";
        "u32";
        "u64";
        "u128";
        "usize";
        "void";
        "noreturn";
        "type";
        "anyerror";
        "comptime_int";
        "comptime_float";
        "c_int";
        "c_uint";
        "c_long";
        "c_ulong";
        "c_short";
        "c_ushort";
        "c_longlong";
        "c_ulonglong";
        "c_longdouble";
      ]
    ~builtins:
      [
        "@import";
        "@cImport";
        "@intCast";
        "@floatCast";
        "@intToFloat";
        "@floatToInt";
        "@TypeOf";
        "@typeName";
        "@sizeOf";
        "@alignOf";
        "@compileError";
        "@compileLog";
        "@panic";
        "@memcpy";
        "@memset";
        "@as";
        "@bitCast";
        "@ptrCast";
        "@enumFromInt";
        "@intFromEnum";
        "@ptrFromInt";
        "@intFromPtr";
        "@errorFromInt";
        "@intFromError";
        "@tagName";
        "@truncate";
        "@splat";
        "@min";
        "@max";
        "@abs";
        "@sqrt";
        "@sin";
        "@cos";
        "@exp";
        "@log";
        "@floor";
        "@ceil";
        "@trunc";
        "@round";
        "@mod";
        "@rem";
        "@divTrunc";
        "@divFloor";
        "@setRuntimeSafety";
        "@embedFile";
        "@field";
        "@hasDecl";
        "@hasField";
        "@This";
        "@call";
        "@clz";
        "@ctz";
        "@popCount";
        "@shlExact";
        "@shrExact";
      ]
    ~constants:[ "true"; "false"; "null"; "undefined" ]
    ~line_comment:[ "//" ]
    ~strings:[ ("\"", "\"", true); ("'", "'", true) ]
    ~raw_strings:[ ("\\\\", "\n") ]
    ~number:
      (Re.alt
         [
           hex_literal ();
           Re.seq [ Re.str "0o"; Re.rep1 (Re.set "01234567") ];
           Re.seq [ Re.str "0b"; Re.rep1 (Re.set "01") ];
           decimal;
         ])
    ~ident:
      (Re.alt
         [ Re.seq [ Re.str "@\""; Re.rep (not_chars "\"\n"); Re.str "\"" ]; identifier ])
    ~operators:
      [
        "++";
        "--";
        "**";
        "==";
        "!=";
        "<=";
        ">=";
        "&&";
        "||";
        "<<=";
        ">>=";
        "<<";
        ">>";
        "|=";
        "&=";
        "^=";
        "%=";
        "*=";
        "/=";
        "+=";
        "-=";
        "->";
        "=>";
        "+";
        "-";
        "*";
        "/";
        "%";
        "<";
        ">";
        "=";
        "!";
        "&";
        "|";
        "^";
        "~";
        "?";
        ":";
        ".";
        "@";
      ]
    ()
