(test
 (name test_fantasy)
 (package charamel)
 (modules
  test_fantasy
  test_anthropic_codec
  test_google_codec
  test_openai_compat_codec
  test_responses_codec
  test_catalog
  test_oauth
  test_retry
  test_provider
  stream_test_support)
 (libraries
  alcotest
  alcotest-lwt
  base64
  charamel.fantasy
  charamel.net
  charamel.os
  cohttp
  digestif
  fmt
  jsont
  jsont.bytesrw
  lwt
  lwt.unix
  net_test_support
  test_support
  uri)
 (deps
  (glob_files data/*)))
