(test
 (name test_tea)
 (package charamel)
 (modules
  test_tea
  test_key
  test_input
  test_cmd_sub
  test_screen
  test_terminal
  test_program)
 (libraries
  charamel.tea
  charamel.colorprofile
  charamel.os
  charamel.ansi
  alcotest
  fmt
  lwt
  lwt.unix
  qcheck-alcotest
  qcheck-core
  test_support
  unix))
