name: build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ocaml-compiler: [5.4.0, 5.5.1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: ocaml/setup-ocaml@e89b2ded52a6e13f50162220cf5fe47290162032 # v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - run: opam install . --deps-only --with-test
      - run: opam install ocamlformat.0.29.0
      - run: opam exec -- dune build --profile release
      - run: opam exec -- dune runtest --profile release
      - run: opam exec -- dune build @fmt
